---

- hosts: all
  become: true
  pre_tasks:

  - name: Dpkg fixing in Ubuntu Servers
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Update and Upgrade remote in Ubuntu servers
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Ubuntu"

  - name: Installing epel-release and dnf
    dnf:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Update and upgrade remote CentOS server
    dnf:
      update_cache: yes
      name:  "*"
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: ubuntu
  become: true
  tasks:

  - name: Installing nagios dependecies and libraries.
    tags: dependecies, libraries
    apt:
      name:
        - autoconf
        - gcc
        - libc6
        - make
        - wget
        - unzip
        - apache2
        - php
        - libapache2-mod-php7.4
        - libgd-dev
        -  openssl
        - libssl-dev
        - autoconf
        - gcc
        - libc6
        - libmcrypt-dev
        - make
        - libssl-dev
        - wget
        - bc
        - gawk
        - dc
        - build-essential
        - snmp
        - libnet-snmp-perl
        - gettext
        - python3-pip
        - python3
      state: latest

  - name: Install passlib python package.
    pip:
      name: passlib

  - name: Directory for Nagios.
    file:
      path: ~/nagios
      state: directory

  - name: Downloading Nagios and Extracting files of Nagios.
    unarchive:
      src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      dest: ~/nagios
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Setting up Nagios Which is Compiling, installing, and creating users and group.
    shell: |
      cd ~/nagios/nagioscore-*
      sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
      sudo make all
      sudo make install-groups-users
      sudo usermod -a -G nagios www-data
      sudo make install
      sudo make install-daemoninit
      sudo make install-commandmode
      sudo make install-config
      sudo make install-webconf
      sudo a2enmod rewrite
      sudo a2enmod cgi

  - name: Downloading nagios plugins and extracting its file.
    unarchive:
      src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
      dest: ~/nagios
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Changing Directories and Compiling. Also, installing nagios plugins.
    shell: |
      cd ~/nagios/nagios-plugins*
      ./tools/setup
      ./configure
      make
      make install

  - name: Starting Nagios and enabled it.
    service:
      name: nagios
      state: restarted
      enabled: true

  - name: Starting httpd and enabled it.
    service:
      name: apache2
      state: restarted
      enabled: true

- hosts: centos
  become: true
  tasks:

  - name: Install passlib python package.
    pip:
      name: passlib

  - name: Directory for Nagios.
    file:
      path: ~/nagios
      state: directory

  - name: Downloading Nagios and Extracting files of Nagios.
    unarchive:
      src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
      dest: ~/nagios
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Setting up nagios which is COmpiling, installing, and creating users and group
    file:
      path: ~/nagios
      state: directory

  - name: Downloading nagios plugins and extracting its file.
    unarchive:
      src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
      dest: ~/nagios
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Changing Directories and compiling. Also, installing nagios plugins
    file:
      path: ~/nagios
      state: directory

  - name: Creating user and password. Also, ensuring permissions are set.
    file:
      path: ~/nagios
      state: directory


  - name: Starting nagios and enabled it
    file:
      path: ~/nagios
      state: directory

  - name: Starting httpd and enabled it
    file:
      path: ~/nagios
      state: directory
